import type { RawaPayError } from "./errors";

/**
 * Result pattern types for predictable error handling.
 */
export type SuccessResult<T> = {
	data: T;
	error: null;
};

export type ErrorResult<E = RawaPayError> = {
	data: null;
	error: E;
};

export type Result<T, E = RawaPayError> = SuccessResult<T> | ErrorResult<E>;

/**
 * Normalized payment statuses across all providers.
 */
export type PaymentStatus = "succeeded" | "pending" | "processing" | "failed" | "cancelled" | "expired";

/**
 * Standardized payment entity returned to developers.
 */
export interface Payment {
	/** Unique transaction identifier generated by RawaPay */
	id: string;
	/** Provider used for this payment, e.g. "jazzcash", "easypaisa" */
	provider: string;
	/** Standardized lifecycle status of the transaction */
	status: PaymentStatus;
	/** Payment amount in Pakistani Rupees (PKR) */
	amount: number;
	/** Raw amount formatted for the gateway */
	rawAmount?: string;
	/** Currency code, always PKR */
	currency: "PKR";
	/** Human-readable memo or developer's order reference */
	description?: string;
	/** Gateway raw response code (e.g. "000") */
	responseCode: string;
	/** Gateway raw response message */
	responseMessage: string;
	/** Bank / Gateway Retrieval Reference Number (RRN) for reconciliation */
	retrievalRefNo?: string;
	/** Full unmodified raw response payload from the gateway */
	raw: Record<string, unknown>;
	/** ISO 8601 creation timestamp */
	createdAt: string;
}

/**
 * Unified error codes categorized across all payment providers.
 */
export type RawaPayErrorCode =
	| "INVALID_REQUEST"
	| "INVALID_PARAMETER"
	| "INVALID_CREDENTIALS"
	| "INVALID_SIGNATURE"
	| "CARD_BLOCKED"
	| "ACCOUNT_INACTIVE"
	| "ACCOUNT_NOT_FOUND"
	| "DUPLICATE_REFERENCE"
	| "INVALID_TIMESTAMP"
	| "INSUFFICIENT_FUNDS"
	| "AUTHENTICATION_FAILED"
	| "TRANSACTION_EXPIRED"
	| "TRANSACTION_CANCELLED"
	| "PAYMENT_PENDING"
	| "LIMIT_EXCEEDED"
	| "PAYMENT_FAILED"
	| "PAYMENT_REJECTED"
	| "GATEWAY_ERROR"
	| "UNKNOWN_ERROR";

/**
 * Common payment parameters required across all drivers.
 */
export interface BasePaymentParams {
	/** Payment amount in PKR */
	amount: number;
	/** Short memo, note, or developer's merchant order reference (e.g. "ORDER-9042") */
	description?: string;
}

/**
 * Parameters for checking transaction status.
 */
export interface GetStatusParams {
	/** Unified payment ID returned by payment.create */
	paymentId: string;
	[key: string]: unknown;
}

/**
 * Interface that each provider driver must implement.
 */
export interface PaymentDriver<TPaymentParams = unknown, TStatusParams = GetStatusParams> {
	/** Unique identifier for the provider driver (e.g. "jazzcash") */
	readonly name: string;

	/** Direct payment initiation */
	createPayment(params: TPaymentParams): Promise<Result<Payment, RawaPayError>>;

	/** Checks status for a previously initiated transaction */
	getStatus(params: TStatusParams): Promise<Result<Payment, RawaPayError>>;

	/** Verifies the cryptographic signature / integrity of an incoming IPN callback */
	verifyCallback?(body: Record<string, unknown>): boolean;
}

/**
 * Execution environment for payment providers and RawaPay.
 */
export type PaymentEnvironment = "sandbox" | "production";

/**
 * Options configurable at top level or per provider.
 */
export interface ProviderOptions {
	/** Target environment mode: "sandbox" or "production" */
	environment?: PaymentEnvironment;
	/** HTTP request timeout in milliseconds */
	timeoutMs?: number;
}

/**
 * Base configuration extended by all provider drivers.
 */
export interface BaseProviderConfig {
	options?: ProviderOptions;
}
